apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        args:
          - >-
            #Install jq CLI on Alpine

            echo You deployed

            sleep 5s
        command:
            - /bin/sh
            - +x
            - '-c'

